# Generated by Django 4.2.3 on 2023-07-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voteuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uservote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtitle', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=40)),
                ('option2', models.CharField(max_length=40)),
                ('option3', models.CharField(max_length=40)),
                ('option4', models.CharField(max_length=40)),
                ('option1val', models.IntegerField(default=0)),
                ('option2val', models.IntegerField(default=0)),
                ('option3val', models.IntegerField(default=0)),
                ('option4val', models.IntegerField(default=0)),
                ('vote', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
