# Generated by Django 4.2.3 on 2023-07-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_remove_vote_user_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteuser',
            name='ochosen',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
