# Generated by Django 4.2.3 on 2023-07-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_voteuser_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteuser',
            name='qid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
